### ISSUE TITLE
exchange platform - uiux enhancement

### ISSUE THREAD

**Issue by uz6r** [thcollective/exchange-platform-web#90]
# todo list

- [x] fix card sequence to make it more readable and appealing

![Desktop - 2](https://user-images.githubusercontent.com/62239643/137076331-5d1c96da-3a17-44da-8b3e-09435e9f71ca.png)

- [x] revamp add to cart popup

![Desktop - 3](https://user-images.githubusercontent.com/62239643/137076306-2f28cf16-ab6a-4184-8085-e0f3d4b9fac2.png)

- [x] remove tabs in products page, and do some enhancement like examples below

![Desktop - 4](https://user-images.githubusercontent.com/62239643/137076262-dd073d00-5ef8-4b30-9be9-bbe31bbe490f.png)

![Desktop - 5](https://user-images.githubusercontent.com/62239643/137076274-95fdb762-eecd-46a7-ae61-e37009d47f0f.png)

![Desktop - 6](https://user-images.githubusercontent.com/62239643/137076283-352e7892-30b1-4b06-a714-a2627973b93b.png)

reference: https://www.figma.com/file/Epw77vLoZ62hzBlAzRGVjd/EXCHANGE-PLATFORM?node-id=0%3A1
